config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#	get 'pages/home', to: 'pages#home'
#	get 'pages/about', to: 'pages#about' 

  #next we will update routes for app example we want http://localhost:3000/ for home and
  #http://localhost:3000/about for about and then run rake routes to check the prefix for path.
	root 'pages#home'
	get 'about', to: 'pages#about'

	get 'signup', to: 'users#new'

	get 'login', to: 'sessions#new' # to: 'action or controller'
	post 'login', to: 'sessions#create' #create new session
	delete 'logout', to: 'sessions#destroy' #destroy session => logout action.

	resources :categories, except: [:destroy]



end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
	validates :user_id, presence: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
  #  @articles = Article.all
  # Do articles pagination
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  #  @articles = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    #debugger
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      #do something
      #change flash[:notice] to flash[:success] for _messages new layout.
      flash[:success] = "Article is successfully created."
      redirect_to article_path(@article)
    else
      render "new"
    end

  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    #respond_to do |format|
      if @article.update(article_params)
      #  format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      #  format.json { render :show, status: :ok, location: @article }
        flash[:success] = "Article was successfully updated."
        redirect_to article_path(@article)
      else
      #  format.html { render :edit }
      #  format.json { render json: @article.errors, status: :unprocessable_entity }
        render 'edit'
      end
    #end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    #respond_to do |format|
    #  format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    #  format.json { head :no_content }
    #end
    flash[:danger] = "Article was successfully destroyed."
    redirect_to articles_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    # This method will check if article belongs to user or not and then let user perform edit or destroy action. 
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <div class="well well-lg">
            <div class="article-title">
              <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
              <%= truncate(article.description, length: 100) %>
              <div class="article-meta-details">
                <small>Created by: <%= article.user.username if article.user %>, 
                  <%= time_ago_in_words(article.created_at) %> ago,
                  last updated: <%= time_ago_in_words(article.updated_at)%> ago 
                </small>
              </div>
            </div>
            <% if article.categories.any? %>
              <p> Categories: <%= render article.categories %> </p>
            <% end %>
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
              <div class="article-actions">
                <%= link_to 'Edit this article', edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to 'Destroy this article', article, method: :delete, 
                                                data: { confirm: 'Are you sure?' }, 
                                                class: "btn btn-xs btn-danger" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
<% end %>

app/views/articles/_form.html.erb
<div class='row'>
  <div class='col-xs-12'>

    <%= form_for(article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <%= render "shared/errors", obj: @article %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
              <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editing article</h1>

<%= render 'form', article: @article %>
<div class= "col-xs-4 col-xs-offset-4">
[<%= link_to 'Cancel request and return to article',  article_path(@article), class: "ln-bottom"%>]
</div>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>
	<% if logged_in? %>
      <div class="row">
        <div class= "col-xs-4 col-xs-offset-4">
          [<%= link_to 'Create a new Article', new_article_path, class: "ln_bottom" %>]
        </div>
      </div>
    <% end %>

app/views/articles/new.html.erb
<h1 align="center">New Article</h1>

<%= render 'form', article: @article %>
<div class= "col-xs-4 col-xs-offset-4">
[<%= link_to 'Cancel request and return to articles listing',  articles_path, class: "ln-bottom"%>]
</div>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %> </h2>
<div class="well col-xs-8 col-xs-offset-2">
 	<% if @article.user %>
 	<ul class="listing">
	    <div class="row center">
	      <div class="col-md-4 col-md-offset-4">
	      	<li>Created by:</li>
	        <li><%= link_to gravatar_for(@article.user), user_path(@article.user)%></li>
	        <li class="article-title">
	          <%= link_to @article.user.username, user_path(@article.user) %>
	        </li>
	        <li>
	          <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
	        </li>
	      </div>
	    </div>
  	</ul>
  	<%end%>
  	<h4 class="center description"><strong>Description:</strong></h4>
 	<hr>
  	<%= simple_format(@article.description) %>
  	<% if @article.categories.any? %>
  		<p>Categories: <%= render @article.categories %></p>
  	<% end %>
  	<div class="article-actions">
  		<% if logged_in? && current_user == @article.user %>
			<%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-xs btn-primary " %>
			<%= link_to 'Delete this article', article_path(@article), method: :delete, data: { confirm: "Are you sure want to delete this article?"}, class: "btn btn-xs btn-danger" %>
			<%= link_to 'View all articles', articles_path, class: "btn btn-xs btn-success" %>
		<% end %>
  	</div>
</div>